
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PMS.Resources.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Booking
{

    public Booking()
    {

        this.AdditionalGuests = new HashSet<AdditionalGuest>();

        this.GuestRewards = new HashSet<GuestReward>();

        this.Invoices = new HashSet<Invoice>();

        this.RoomBookings = new HashSet<RoomBooking>();

    }


    public int ID { get; set; }

    public int PropertyID { get; set; }

    public Nullable<System.DateTime> CheckinTime { get; set; }

    public Nullable<System.DateTime> CheckoutTime { get; set; }

    public Nullable<int> NoOfAdult { get; set; }

    public Nullable<int> NoOfChild { get; set; }

    public string GuestRemarks { get; set; }

    public string TransactionRemarks { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public string LastUpdatedBy { get; set; }

    public Nullable<System.DateTime> LastUpdatedOn { get; set; }

    public string Status { get; set; }

    public Nullable<bool> ISHOURLYCHECKIN { get; set; }

    public Nullable<int> HOURSTOSTAY { get; set; }

    public Nullable<int> RateTypeId { get; set; }



    public virtual ICollection<AdditionalGuest> AdditionalGuests { get; set; }

    public virtual Property Property { get; set; }

    public virtual RateType RateType { get; set; }

    public virtual ICollection<GuestReward> GuestRewards { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; }

    public virtual ICollection<RoomBooking> RoomBookings { get; set; }

}

}
