
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PMS.Resources.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Guest
{

    public Guest()
    {

        this.Addresses = new HashSet<Address>();

        this.GuestMappings = new HashSet<GuestMapping>();

        this.GuestRewards = new HashSet<GuestReward>();

        this.Invoices = new HashSet<Invoice>();

        this.RoomBookings = new HashSet<RoomBooking>();

    }


    public int ID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public Nullable<long> MobileNumber { get; set; }

    public string EmailAddress { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public string Gender { get; set; }

    public string PhotoPath { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public string LastUpdatedBy { get; set; }

    public Nullable<System.DateTime> LastUpdatedOn { get; set; }



    public virtual ICollection<Address> Addresses { get; set; }

    public virtual ICollection<GuestMapping> GuestMappings { get; set; }

    public virtual ICollection<GuestReward> GuestRewards { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; }

    public virtual ICollection<RoomBooking> RoomBookings { get; set; }

}

}
