//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Resources.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestMapping
    {
        public int ID { get; set; }
        public int IDTYPEID { get; set; }
        public int GUESTID { get; set; }
        public string IDDETAILS { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public System.DateTime IdExpiryDate { get; set; }
        public string IdIssueState { get; set; }
        public string IdIssueCountry { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual IDType IDType { get; set; }
    }
}
