//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Resources.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.Bookings = new HashSet<Booking>();
            this.RateTypes = new HashSet<RateType>();
            this.Rooms = new HashSet<Room>();
            this.RoomPricings = new HashSet<RoomPricing>();
            this.RoomTypes = new HashSet<RoomType>();
        }
    
        public int ID { get; set; }
        public string PropertyDetails { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<RateType> RateTypes { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<RoomPricing> RoomPricings { get; set; }
        public virtual ICollection<RoomType> RoomTypes { get; set; }
    }
}
