//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Resources.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<int> RateTypeID { get; set; }
        public Nullable<int> RoomTypeID { get; set; }
        public Nullable<int> InputKeyHours { get; set; }
        public Nullable<decimal> Value { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual RateType RateType { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
